Added updating user info and reformated some code
RuslanMonar/SportsHub_BE pull request #11
Opened 2021-08-23 00:53 UTC by qwerhnatkiv

2021-08-24 20:39 UTC, RuslanMonar approved these changes
Всьо ок

2021-08-25 12:19 UTC, realoneee1 approved these changes

2021-08-25 14:14 UTC, merged

2021-08-25 14:27 UTC, Markian-DV requested changes

2021-08-25 14:27 UTC, Markian-DV commented on API/Controllers/UserController.cs
> +                );
коли юзер змінюватиме свою аватарку він передаваиме фотографію а не url на неї

2021-08-25 14:27 UTC, Markian-DV commented on API/Controllers/UserController.cs
> +                );
це не ок повертати анонімний об"єкт, використай DTO

2021-08-25 14:27 UTC, Markian-DV commented on Application/AuthResult.cs
наввіщо тут інтерфейс?